#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Fri Jul 17 22:43:55 CST 2026
allowUnknownShaders=false
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.8.1 + EuphoriaPatches_1.9.3
